name : Test & Build

on:
    push:
      branches-ignore:
        - main
        - develop
    pull_request:
      branches:
        - main
        - develop
  
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
              - name: Checkout code
                uses: actions/checkout@v4
              - name : Set up go
                uses: actions/setup-go@v5
                with:
                    go-version: '1.24'
              - name: lint
                uses: golangci/golangci-lint-action@v6.4.0
                with:
                    only-new-issues: true
                    args: --timeout=30m
              - name: Run tests
                run: go test -v -count=1 -p 4 -coverprofile=coverage.txt -covermode=atomic ./...
                env:
                    MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
              - name: Upload coverage reports to Codecov
                uses: codecov/codecov-action@v5
                with:
                  token: ${{ secrets.CODECOV_TOKEN }}
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
              - name: Checkout code
                uses: actions/checkout@v4
              - name: Set up go
                uses: actions/setup-go@v5
                with:
                    go-version: '1.24'
              - name: Build
                run: go build -o . ./cmd/app/main.go
    docker-build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build Docker image
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/feed-pulse-back:${{ github.sha }} .